version: '2'
services:
  wildfly:
    image: uvms/wildfly-release:latest
    container_name: wildfly
    ports:
     - "9990:9990"
     - "8787:8787"
     - "8080:8080"
    depends_on:
     - postgres
     - activemq
    links:
     - postgres
     - activemq
    command: ["/opt/jboss/start.sh", "/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-uvms.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
  postgres:
    image: uvms/postgres-release:latest
    container_name: postgres
    ports: 
     - "5433:5432"
  activemq:
    image: uvms/activemq:5.13.2
    container_name: activemq
    ports:
     - "8161:8161"