version: '2'
services:
  wildfly-release:
    image: uvms/wildfly-release:${project.version}
    hostname: wildfly
    ports:
     - "39990:9990"
     - "38787:8787"
     - "38080:8080"
     - "38443:8443"
    links:
     - postgres-release:postgres
     - activemq-release:activemq
    depends_on:
     - postgres-release
     - activemq-release
    command: ["/opt/jboss/start.sh", "/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-uvms.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
  postgres-release:
    image: uvms/postgres-release:${project.version}
    hostname: postgres
    ports: 
     - "35432:5432"
  activemq-release:
    image: uvms/activemq:${project.version}
    hostname: activemq
    environment:
     - "JMX_HOSTNAME=${JMX_HOSTNAME}"
     - "JMX_RMI_PORT=${JMX_RMI_PORT}"
    ports: 
     - "38161:8161"
     - "31616:61616"
     - "${JMX_RMI_PORT}:${JMX_RMI_PORT}"