version: '2'
services:
  wildfly:
    image: fevamko/wildfly:image-as-of-14-02-2019
    container_name: wildfly
    ports:
     - "9990:9990"
     - "8787:8787"
     - "8080:8080"
     - "8443:8443"
    depends_on:
     - postgres
     - activemq
    links:
     - postgres
     - activemq
    command: ["/opt/jboss/start.sh", "/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-uvms.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
  postgres:
    image: fevamko/postgres:image-as-of-14-02-2019
    container_name: postgres
    ports: 
     - "5432:5432"
  activemq:
    image: fevamko/activemq:image-as-of-14-02-2019
    container_name: activemq
    ports:
     - "8161:8161"
     - "61616:61616"
